// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9KPrQynYwnIOaaybvL8fAZHifatC3JlA',
    appId: '1:31779898080:web:be0359bc6716afa9760685',
    messagingSenderId: '31779898080',
    projectId: 'pharma-6316e',
    authDomain: 'pharma-6316e.firebaseapp.com',
    storageBucket: 'pharma-6316e.appspot.com',
    measurementId: 'G-Z30JKWJM8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMY7CK2SeXbpYLvuqcm64Ulx8k5ckR7_s',
    appId: '1:31779898080:android:7cd374ccc01afb1d760685',
    messagingSenderId: '31779898080',
    projectId: 'pharma-6316e',
    storageBucket: 'pharma-6316e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS4zVVUycV5jS1W-cIc2JMT-plQ20G3bQ',
    appId: '1:31779898080:ios:6444623900fa3b60760685',
    messagingSenderId: '31779898080',
    projectId: 'pharma-6316e',
    storageBucket: 'pharma-6316e.appspot.com',
    iosBundleId: 'com.example.pharma',
  );
}
